services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: avancaif
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data
volumes:
  postgres_data2:
