CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    name VARCHAR(255) UNIQUE,
    PASSWORD NVARCHAR2(128) NOT NULL,
    ENABLED CHAR(1) CHECK (ENABLED IN ('Y','N') ) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    user_id SERIAL NOT NULL,
    authority VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS BADGES (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    technologies TEXT[] NOT NULL,
    image_url VARCHAR(500) NOT NULL
);

-- ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_UNIQUE UNIQUE (user_id, authority);
-- ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITIES_FK1 FOREIGN KEY (user_id) REFERENCES USERS
